# Generated by Django 5.1.6 on 2025-03-05 17:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('style_id', models.CharField(max_length=20)),
                ('order_received_from', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinishingAndPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_number', models.CharField(max_length=50)),
                ('job_worker_name', models.CharField(max_length=100)),
                ('issued_challan_quantity', models.IntegerField()),
                ('packed_quantity', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='FabricPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_purchase_date', models.DateField(default=datetime.date.today)),
                ('purchased_from', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(max_length=50)),
                ('fabric_detail', models.CharField(max_length=100)),
                ('fabric_length', models.CharField(max_length=20)),
                ('fabric_dyer', models.CharField(max_length=100)),
                ('challan_number', models.CharField(max_length=50)),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_quantity', models.IntegerField()),
                ('balance_fabric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(default=datetime.date.today)),
                ('dispatched_to', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='ClothCutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_number', models.CharField(max_length=50)),
                ('job_worker_name', models.CharField(max_length=100)),
                ('fabric_detail', models.CharField(max_length=100)),
                ('fabric_length', models.CharField(max_length=20)),
                ('issued_challan_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('balance_quantity', models.IntegerField()),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('received_challan_number', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingAndDyeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_number', models.CharField(max_length=50)),
                ('dyer_printer_name', models.CharField(max_length=100)),
                ('fabric_detail', models.CharField(max_length=100)),
                ('fabric_length', models.CharField(max_length=20)),
                ('issued_challan_quantity', models.IntegerField()),
                ('shrinkage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.IntegerField()),
                ('balance_quantity', models.IntegerField()),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('received_challan_number', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Stitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_number', models.CharField(max_length=50)),
                ('job_worker_name', models.CharField(max_length=100)),
                ('extra_work_name', models.CharField(max_length=100)),
                ('issued_challan_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('balance_quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
    ]
