# Generated by Django 5.1.6 on 2025-03-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_clothcutting_user_dispatch_user_fabricpurchased_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printinganddyeing',
            old_name='shrinkage',
            new_name='shrinkage_in_percentage',
        ),
    ]
