# Generated by Django 5.1.6 on 2025-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_shrinkage_printinganddyeing_shrinkage_in_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
