# Generated by Django 5.1.6 on 2025-03-09 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitching',
            name='received_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clothcutting',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clothcutting',
            name='balance_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='balance_fabric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='finishingandpacking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='finishingandpacking',
            name='rejected',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='balance_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stitching',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stitching',
            name='balance_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
