# Generated by Django 5.1.6 on 2025-03-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_stitching_received_date_alter_clothcutting_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothcutting',
            options={'verbose_name_plural': 'Cloth Cutting'},
        ),
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name_plural': 'Dispatch'},
        ),
        migrations.AlterModelOptions(
            name='fabricpurchased',
            options={'verbose_name_plural': 'Fabric Purchased'},
        ),
        migrations.AlterModelOptions(
            name='finishingandpacking',
            options={'verbose_name_plural': 'Finishing and Packing'},
        ),
        migrations.AlterModelOptions(
            name='printinganddyeing',
            options={'verbose_name_plural': 'Printing and Dyeing'},
        ),
        migrations.AlterModelOptions(
            name='stitching',
            options={'verbose_name_plural': 'Stitching'},
        ),
    ]
