# Generated by Django 5.1.6 on 2025-04-03 14:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_clothcutting_options_alter_dispatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fabric Purchased', 'Fabric Purchased'), ('Printing and Dyeing', 'Printing and Dyeing'), ('Cloth Cutting', 'Cloth Cutting'), ('Stitching', 'Stitching'), ('Extra Work', 'Extra Work'), ('Finishing and Packing', 'Finishing and Packing'), ('Dispatched', 'Dispatched')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('issued_challan_number', models.CharField(max_length=50)),
                ('style_id', models.CharField(max_length=20)),
                ('job_worker_name', models.CharField(max_length=100)),
                ('extra_work_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('balance_quantity', models.IntegerField(blank=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
    ]
