# Generated by Django 5.1.6 on 2025-04-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_extrawork_style_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrawork',
            old_name='quantity',
            new_name='issued_challan_quantity',
        ),
    ]
