# Generated by Django 5.1.6 on 2025-04-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_order_size_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinganddyeing',
            name='issued_challan_number',
        ),
    ]
