# Generated by Django 5.1.6 on 2025-04-23 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_printinganddyeing_issued_challan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinganddyeing',
            name='balance_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_challan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='shrinkage_in_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
