# Generated by Django 5.1.6 on 2025-04-23 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_printinganddyeing_balance_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='box_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='balance_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_challan_number',
            field=models.CharField(default='adfadf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='received_quantity',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printinganddyeing',
            name='shrinkage_in_percentage',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=10),
            preserve_default=False,
        ),
    ]
