# Generated by Django 5.1.6 on 2025-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_dispatch_box_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinganddyeing',
            name='balance_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
