# Generated by Django 5.1.6 on 2025-04-24 16:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_printinganddyeing_received_challan_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fabric Purchased', 'Fabric Purchased'), ('Printing and Dyeing Sent', 'Printing and Dyeing Sent'), ('Printing and Dyeing Received', 'Printing and Dyeing Received'), ('Cloth Cutting', 'Cloth Cutting'), ('Stitching', 'Stitching'), ('Extra Work', 'Extra Work'), ('Finishing and Packing', 'Finishing and Packing'), ('Dispatched', 'Dispatched')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='PrintingAndDyeingSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_challan_date', models.DateField(default=datetime.date.today)),
                ('dyer_printer_name', models.CharField(max_length=100)),
                ('fabric_detail', models.CharField(max_length=100)),
                ('fabric_length', models.CharField(max_length=20)),
                ('issued_challan_quantity', models.IntegerField()),
                ('received', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Printing and Dyeing Sent',
            },
        ),
        migrations.CreateModel(
            name='PrintingAndDyeingReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrinkage_in_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.IntegerField()),
                ('balance_quantity', models.IntegerField(blank=True)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('received_challan_number', models.CharField(help_text='Each line represents the box number', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('printing_and_dyeing_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.printinganddyeingsent')),
            ],
            options={
                'verbose_name_plural': 'Printing and Dyeing Received',
            },
        ),
        migrations.DeleteModel(
            name='PrintingAndDyeing',
        ),
    ]
