# Generated by Django 5.1.6 on 2025-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_order_status_printinganddyeingsent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinganddyeingreceived',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='printinganddyeingreceived',
            name='rate',
        ),
        migrations.AddField(
            model_name='printinganddyeingsent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='printinganddyeingsent',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
