# Generated by Django 5.1.6 on 2025-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_printinganddyeingreceived_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinganddyeingsent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printinganddyeingsent',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
