# Generated by Django 5.1.6 on 2025-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_printinganddyeingsent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinganddyeingreceived',
            name='received_challan_number',
            field=models.CharField(max_length=50),
        ),
    ]
