# Generated by Django 5.1.6 on 2025-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_printinganddyeingreceived_received_challan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
