# Generated by Django 5.1.6 on 2025-08-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_order_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_2xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_3xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_4xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_5xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricpurchased',
            name='quantity_xs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
