# Generated by Django 5.1.6 on 2025-08-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_fabricpurchased_quantity_2xl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_2xl',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_3xl',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_4xl',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_5xl',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_l',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_m',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_s',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_xl',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='quantity_xs',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_2xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_3xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_4xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_5xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_xs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
