# Generated by Django 5.1.6 on 2025-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_remove_fabricpurchased_quantity_2xl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printinganddyeingreceived',
            name='received_quantity2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printinganddyeingreceived',
            name='received_quantity3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printinganddyeingreceived',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
