# Generated by Django 5.1.6 on 2025-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_printinganddyeingreceived_received_quantity2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='challan_number',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='issued_challan_date',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_10xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_6xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_7xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_8xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_9xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='issued_challan_quantity',
            field=models.IntegerField(help_text='Quantity of fabric to buy mentioned in challan.'),
        ),
        migrations.AlterField(
            model_name='fabricpurchased',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of fabric received after purchase.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL')], default='S', max_length=4),
        ),
    ]
