# Generated by Django 5.1.6 on 2025-08-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_remove_fabricpurchased_challan_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='balance_fabric',
        ),
        migrations.RemoveField(
            model_name='fabricpurchased',
            name='issued_challan_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
