# Generated by Django 5.1.6 on 2025-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_remove_fabricpurchased_balance_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printinganddyeingsent',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printinganddyeingsent',
            name='issued_challan_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
