# Generated by Django 5.1.6 on 2025-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_printinganddyeingsent_received_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinganddyeingreceived',
            name='received_quantity2',
        ),
        migrations.RemoveField(
            model_name='printinganddyeingreceived',
            name='received_quantity3',
        ),
        migrations.RemoveField(
            model_name='printinganddyeingsent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='printinganddyeingsent',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='printinganddyeingsent',
            name='received_quantity',
        ),
        migrations.AddField(
            model_name='printinganddyeingreceived',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='printinganddyeingreceived',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printinganddyeingsent',
            name='issued_challan_quantity',
            field=models.IntegerField(),
        ),
    ]
